export enum Languages {
  JavasScript = 'JavaScript',
  TypeScript = 'TypeScript',
  Java = 'Java',
  CSharp = 'C#',
  CPlusPlus = 'C++',
  TailwindCSS = 'TailwindCSS',
  Firebase = 'Firebase',
  Bootstrap = 'Bootstrap',
  CSS = 'CSS',
  HTML = 'HTML',
  SWIFT = 'SWIFT',
  Angular = 'Angular',
  Python = 'Python',
  Sklearn = 'Sklearn',
  Pandas = 'Pandas',
  Numpy = 'Numpy',
  Matplotlib = 'Matplotlib',
  OpenCV = 'OpenCV',
  ThreeJS = 'ThreeJS',
  TenserFlow = 'TenserFlow',
  Keras = 'Keras',
  AndroidStudio = 'Android Studio',
  Kotlin = 'Kotlin',
  API = 'API',
}
